title: Optipeople
description: >- # Ignore lines up to next function
  Producerer din virksomhed optimalt hver eneste dag og på hver eneste maskine?
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://optipeople.dk" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:title/
name: /OptiPeople
assetpath: /assets/uploads/
# Build settings
markdown: kramdown
sass:
  style: compressed
collections: #category related
  category:
    output: true
defaults: #category related
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
plugins:  #Custom plugins
  - jekyll-feed
  - jekyll-toc
  - jekyll-youtube
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
toc: #from the jekyll toc plugin
  min_level: 2 # default: 1
  max_level: 2 # default: 6
